CUDA_VISIBLE_DEVICES=0 python src/main_gnn_fsca_ir.py \
    --wd_project fsca-cla-log00 \
    --batch_size=64 \
    --comment="classification from Scratch" \
    --training_flag=1 \
    --d_ff=512 \
    --d_l_comp=512 \
    --d_model=768 \
    --data_class=tsra \
    --dropout=0.1 \
    --epochs=50 \
    --key_metric=accuracy \
    --layer_index=6*0_1_4*0_1_4 \
    --lr=0.0001 \
    --model=FSCA \
    --data=MIMIC \
    --seq_len=2880 \
    --feature_dim=96 \
    --optimizer=RAdam \
    --output_dir=experiments/ \
    --patch_size_stride="16 8" \
    --pattern=TRAIN \
    --pos_encoding=learnable \
    --records_file=Classification_records.xls \
    --revin_flag=0 \
    --seed=42 \
    --task=classification \
    --test_flag=0 \
    --val_interval=1 \
    --val_pattern=TEST \
    --w_l2s_flag=0 \
    --w_l2s_v=0.0001 \
    --wandb_flag=0 \
    --quantization 0.016 \
    --classif \
