CUDA_VISIBLE_DEVICES=0 python -u run_mTAN_encoder.py \
  --task_name ir_classification_mTAN \
  --is_training 1 \
  --root_path ../../datasets/P12 \
  --data_path P12 \
  --model_id few_shot_P12_1_S2IPLLM_mTAN_encoder \
  --model S2IPLLM_mTAN_encoder \
  --data P12 \
  --data_split_path ../../datasets/P12data/splits/phy12_split1.npy \
  --number_variable 41 \
  --features M \
  --num_ref_points 256 \
  --feature_dim 41 \
  --label_len 1 \
  --pred_len 0 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --d_model 768 \
  --learning_rate 0.0001 \
  --loss 'CE' \
  --patch_size 16 \
  --patience 10 \
  --stride 8 \
  --add_prompt 1 \
  --prompt_length 4 \
  --batch_size 32 \
  --sim_coef -0.05 \
  --pool_size  1000 \
  --trend_length 96 \
  --seasonal_length 96 \
  --num_classes 2 \
  --classif \
  --num_heads_mtan 1 \
  --learn_emb \
  --percent 10 \
