CUDA_VISIBLE_DEVICES=0 python -u run.py \
  --seed 123 \
  --task_name ir_classification \
  --is_training 1 \
  --root_path ./data/activity \
  --data_path activity \
  --model_id activity \
  --model S2IPLLM \
  --data activity \
  --data_split_path ./activity_split1.npy \
  --number_variable 12 \
  --features M \
  --seq_len 221 \
  --feature_dim 12 \
  --label_len 1 \
  --pred_len 0 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --d_model 768 \
  --learning_rate 0.001 \
  --loss 'CE' \
  --patch_size 16 \
  --patience 10 \
  --stride 8 \
  --add_prompt 1 \
  --prompt_length 4 \
  --batch_size 128 \
  --sim_coef -0.05 \
  --pool_size  1000 \
  --percent 100 \
  --trend_length 24 \
  --seasonal_length 24 \
  --num_classes 7 \
  --classif \
  --classify-pertp \
