python run.py \
  --seed 12 \
  --task_name classification \
  --is_training 1 \
  --data activity \
  --root_path ./data/activity \
  --data_path activity \
  --data_split_path ./activity_split2.npy \
  --model_id Activity \
  --seq_len 50 \
  --num_variables 12 \
  --itr 1 \
  --train_epochs 100 \
  --batch_size 128 \
  --patience 10 \
  --learning_rate 0.001 \
  --des 'Exp' \
  --loss 'CE' \
  --lradj type1 \
  --num_classes 7 \
  --classif \
  --classify-pertp \
