CUDA_VISIBLE_DEVICES=0 python -u run.py \
  --task_name ir_classification \
  --is_training 0 \
  --root_path ./data/PhysioNet \
  --data_path PhysioNet \
  --model_id PhysioNet \
  --data PhysioNet \
  --seq_len 2881 \
  --des 'Exp' \
  --itr 1 \
  --learning_rate 0.0001 \
  --loss 'CE' \
  --batch_size 28 \
  --num_classes 2 \
  --n 8000 \
  --quantization 0.016 \
  --classif
